### ISSUE TITLE
Remove the sns:Publish statement from the IAM policy

### ISSUE THREAD

**Issue by sam9191** [awsdocs/aws-personal-health-dashboard#4]
On this page:
https://github.com/awsdocs/aws-personal-health-dashboard/blob/main/doc_source/cloudwatch-events-health.md
Please delete this part from the IAM policy as it's not needed and confuses readers:
```
    {
      "Effect": "Allow",
      "Action": [
        "sns:Publish"
      ],
      "Resource": [
        "arn:aws:sns:*:*:Automation*"
      ]
    },
```

**Comment by alextruo** [comment]
Hello, this has been fixed. Thank you for letting us know about this issue!
